baseurl = "https://example.com/"
title = "Murphy Salvado"
theme = "arabica-master"
languageCode = "en-us"
copyright = "Murphy Salvado"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Murphy Salvado"
    profile = ""
    email = "murphysalvado@gmail.com"
    nick = "Murphy"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Murphy Salvado"
    description = ""
    github = "https://github.com/murphysalvado"
    gitlab = ""
    linkedin = ""
    gplus = ""
    twitter = "https://twitter.com/murphysalvado"
    stackoverflow = ""
    microblog = "https://micro.blog/murphysalvado"
    feedurl = ""
    webmentionEndpoint = ""
    pingbackEndpoint = ""
    micropubEndpoint = ""
    email = "murphysalvado@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3


